package com.nemezor.nemgine.misc;

public enum Anchors {

	LEFT, RIGHT, TOP, BOTTOM, LEFT_RIGHT, TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT,
	BOTTOM_RIGHT, TOP_BOTTOM, TOP_LEFT_RIGHT, BOTTOM_LEFT_RIGHT, LEFT_TOP_BOTTOM,
	RIGHT_TOP_BOTTOM, LEFT_RIGHT_TOP_BOTTOM;
	
}
